"""add_claim_group_to_expenses

Revision ID: 0ce076ac01a9
Revises: f064ff647124
Create Date: 2026-04-14 13:16:56.458488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce076ac01a9'
down_revision = 'f064ff647124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_group', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_claim_group'), ['claim_group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_claim_group'))
        batch_op.drop_column('claim_group')

    # ### end Alembic commands ###
