"""Add pension projection fields and retirement planning

Revision ID: 0fdcc9029811
Revises: be2e49533d06
Create Date: 2026-02-03 20:25:02.478205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdcc9029811'
down_revision = 'be2e49533d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pension_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_projection', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('scenario_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('growth_rate_used', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('growth_percent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('pensions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retirement_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_contribution', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('projected_value_at_retirement', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pensions', schema=None) as batch_op:
        batch_op.drop_column('projected_value_at_retirement')
        batch_op.drop_column('monthly_contribution')
        batch_op.drop_column('retirement_age')

    with op.batch_alter_table('pension_snapshots', schema=None) as batch_op:
        batch_op.alter_column('growth_percent',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('growth_rate_used')
        batch_op.drop_column('scenario_name')
        batch_op.drop_column('is_projection')

    # ### end Alembic commands ###
