"""add manual override fields to income

Revision ID: 1348150ce6ab
Revises: d3f258dc3ab9
Create Date: 2026-02-03 13:28:23.671284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1348150ce6ab'
down_revision = 'd3f258dc3ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual_override', sa.Boolean(), nullable=True, server_default='0'))
    
    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_manual_deductions', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('manual_tax_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('manual_ni_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('manual_employer_pension', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('manual_employee_pension', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('manual_take_home', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.drop_column('manual_take_home')
        batch_op.drop_column('manual_employee_pension')
        batch_op.drop_column('manual_employer_pension')
        batch_op.drop_column('manual_ni_monthly')
        batch_op.drop_column('manual_tax_monthly')
        batch_op.drop_column('use_manual_deductions')
    
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('is_manual_override')
    # ### end Alembic commands ###
