"""Add payment_day to mortgage products

Revision ID: 13bd6ec7f3ba
Revises: 29bee18cb03d
Create Date: 2026-02-03 22:18:33.841620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bd6ec7f3ba'
down_revision = '29bee18cb03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.drop_column('payment_day')

    # ### end Alembic commands ###
