"""add recurring_income_id to income

Revision ID: 28c246472c52
Revises: 1348150ce6ab
Create Date: 2026-02-03 14:13:48.701587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c246472c52'
down_revision = '1348150ce6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_income_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_income_recurring_income', 'recurring_income', ['recurring_income_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_recurring_income', type_='foreignkey')
        batch_op.drop_column('recurring_income_id')

    # ### end Alembic commands ###
