"""Add account and transaction links to mortgage system

Revision ID: 29bee18cb03d
Revises: 0fdcc9029811
Create Date: 2026-02-03 22:07:39.284215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bee18cb03d'
down_revision = '0fdcc9029811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mortgage_product_account', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('mortgage_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mortgage_snapshot_transaction', 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mortgage_snapshot_transaction', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mortgage_product_account', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
