"""Add bank account linking to loans

Revision ID: 2a85d13def97
Revises: 96a7b9051c0d
Create Date: 2026-01-28 15:57:46.750040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a85d13def97'
down_revision = '96a7b9051c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_credit_card_transactions_bank_transaction', 'transactions', ['bank_transaction_id'], ['id'])

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_loan_payments_bank_transaction', 'transactions', ['bank_transaction_id'], ['id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_payment_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_loans_default_payment_account', 'accounts', ['default_payment_account_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_default_payment_account', type_='foreignkey')
        batch_op.drop_column('default_payment_account_id')

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loan_payments_bank_transaction', type_='foreignkey')
        batch_op.drop_column('bank_transaction_id')

    with op.batch_alter_table('credit_card_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credit_card_transactions_bank_transaction', type_='foreignkey')
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
