"""Add forecasting fields for fuel integration

Revision ID: 4e3631538b5a
Revises: acb1e529248a
Create Date: 2026-01-30 11:13:00.998292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3631538b5a'
down_revision = 'acb1e529248a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fuel_records_transaction', 'transactions', ['linked_transaction_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_forecasted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vehicles_fuel_account', 'accounts', ['fuel_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicles_fuel_account', type_='foreignkey')
        batch_op.drop_column('fuel_account_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_forecasted')

    with op.batch_alter_table('fuel_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fuel_records_transaction', type_='foreignkey')
        batch_op.drop_column('linked_transaction_id')

    # ### end Alembic commands ###
