"""Add vendor_id and category_id to mortgage products

Revision ID: 803cec4fb186
Revises: 13bd6ec7f3ba
Create Date: 2026-02-03 22:22:13.267869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803cec4fb186'
down_revision = '13bd6ec7f3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mortgage_product_vendor', 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key('fk_mortgage_product_category', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mortgage_products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mortgage_product_vendor', type_='foreignkey')
        batch_op.drop_constraint('fk_mortgage_product_category', type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
