"""Add category_id to recurring_income

Revision ID: 953c136cfbc2
Revises: 803cec4fb186
Create Date: 2026-02-03 22:50:25.712031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953c136cfbc2'
down_revision = '803cec4fb186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recurring_income_category', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recurring_income_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
