"""Add starting_mileage to vehicles

Revision ID: acb1e529248a
Revises: 3087325ab8da
Create Date: 2026-01-30 11:01:11.485621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb1e529248a'
down_revision = '3087325ab8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_activity_types', schema=None) as batch_op:
        batch_op.alter_column('occurs_monday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_tuesday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_wednesday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_thursday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_friday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_saturday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_sunday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('transaction_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'28'"))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_payday_period'))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_mileage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('starting_mileage')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_payday_period'), ['payday_period'], unique=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('transaction_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'28'"))

    with op.batch_alter_table('child_activity_types', schema=None) as batch_op:
        batch_op.alter_column('occurs_sunday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_saturday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_friday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_thursday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_wednesday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_tuesday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('occurs_monday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
