"""Add linked_transaction_id to transactions

Revision ID: bb129c35254e
Revises: 2a85d13def97
Create Date: 2026-01-29 12:08:52.819299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb129c35254e'
down_revision = '2a85d13def97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_linked_transaction_id', 'transactions', ['linked_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_linked_transaction_id', type_='foreignkey')
        batch_op.drop_column('linked_transaction_id')

    # ### end Alembic commands ###
