"""add_claim_group_to_transactions

Revision ID: c01178bbb3c4
Revises: 0ce076ac01a9
Create Date: 2026-04-14 14:15:20.169003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01178bbb3c4'
down_revision = '0ce076ac01a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_group', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_claim_group'), ['claim_group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_claim_group'))
        batch_op.drop_column('claim_group')

    # ### end Alembic commands ###
