"""add tax_settings table

Revision ID: d3f258dc3ab9
Revises: d84f04dc86e5
Create Date: 2026-02-03 12:35:01.034466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f258dc3ab9'
down_revision = 'd84f04dc86e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tax_year', sa.String(length=9), nullable=False),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('personal_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('basic_rate_limit', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('higher_rate_limit', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('basic_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('higher_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('additional_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('ni_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('ni_upper_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('ni_basic_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('ni_additional_rate', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tax_year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_settings')
    # ### end Alembic commands ###
