"""add income_id to transactions

Revision ID: d84f04dc86e5
Revises: 13cd1bc1a867
Create Date: 2026-02-03 12:15:43.496687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84f04dc86e5'
down_revision = '13cd1bc1a867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_income_id', 'income', ['income_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_income_id', type_='foreignkey')
        batch_op.drop_column('income_id')
    # ### end Alembic commands ###
