"""add property valuation snapshots

Revision ID: f064ff647124
Revises: a1c3f5e7b9d2
Create Date: 2026-03-01 22:09:21.069532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f064ff647124'
down_revision = 'a1c3f5e7b9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_family_id'), ['family_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_family_id'), ['family_id'], unique=False)

    with op.batch_alter_table('vendor_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_types_family_id'), ['family_id'], unique=False)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_name'))
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_family_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_name'))
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=1)

    with op.batch_alter_table('vendor_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_types_family_id'))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_family_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_family_id'))

    # ### end Alembic commands ###
